---
title: "Homework 3"
author: "David Istvan"
date: "3 July 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
B = 5000
x <- runif(n = B, min = -1, max = 1)
y <- runif(n = B, min = -1, max = 1)
```

```{r}
point = matrix(runif(2*B, -1, 1), B, 2)

test = 0
for (i in 1:B) {
  if(point[i,1]^2+point[i,2]^2 <= 1){
     test = test + 1}
}
print(test/5000*4)
```

```{r}
find_pi = function(B = 5000, seed = 10, make_plot = TRUE){
  # Control seed
  set.seed(seed)
  
  # Simulate B points
  point = matrix(runif(2*B, -1, 1), B, 2)
  c_points = 0
  for (i in 1:B) {
  if(point[i,1]^2+point[i,2]^2 <= 1){
     c_points = c_points + 1}
}
 hat_pi = c_points/5000*4
 return(hat_pi)
}

find_pi()
```

```{r}
magnitude = function(x, y) {
  stopifnot(isTRUE(all.equal(length(x),length(y))))
  return (sqrt(x^2 + y^2))
}
library(plotrix)
monte.carlo.pi<-function(n,draw=FALSE)
{
  circle.points<-0
  square.points<-0
  x<-runif(n,-1,1)
  y<-runif(n,-1,1)
  for (i in 1:n)
  {
    #if ((x[i])^2 + (y[i])^2 <=1)
    if (magnitude(x[i],y[i])<=1)
    {
      circle.points<-circle.points+1
      square.points<-square.points+1
    } else
    {
      square.points<-square.points+1
    }
  }
  if (draw==TRUE)
  {
    plot.new()
    frame()
    plot(x,y,asp=1,xlim=c(-1,1),ylim=c(-1,1))
    draw.circle(0,0,1,nv=1000,border=NULL,col=NA,lty=1,lwd=1)
    rect(-1,-1,1,1)
    return(4*circle.points / square.points)
  }
}

monte.carlo.pi(100,T)
```